### ISSUE TITLE
Some Problems need to be fixed

### ISSUE THREAD

**Issue by hamza-bouqssim** [CrispLake/so_long#1]
i have checked your so_long project
i think you have to fix some errors
you have to depend on header file (because if we have changed something in header , it should be remaked)
and  a segmentation fault occured when changing something in your xpm files, you have to protect xpm_file_to_image function
otherwise you did an amazing work, keep it up

**Comment by CrispLake** [comment]
Thank you for pointing out these errors. They are fixed in the latest commit (173112e)
